countries = {
    "af" : {"nameEn": "Afghanistan", "namePt": "Afeganistão"},
    "za" : {"nameEn": "South Africa", "namePt": "África do Sul"},
    "al" : {"nameEn": "Albania", "namePt": "Albânia"},
    "de" : {"nameEn": "Germany", "namePt": "Alemanha"},
    "ad" : {"nameEn": "Andorra", "namePt": "Andorra"},
    "ao" : {"nameEn": "Angola", "namePt": "Angola"},
    "ai" : {"nameEn": "Anguilla", "namePt": "Anguilla"},
    "ag" : {"nameEn": "Antigua and Barbuda", "namePt": "Antígua e Barbuda"},
    "sa" : {"nameEn": "Saudi Arabia", "namePt": "Arábia Saudita"},
    "dz" : {"nameEn": "Algeria", "namePt": "Argélia"},
    "ar" : {"nameEn": "Argentina", "namePt": "Argentina"},
    "am" : {"nameEn": "Armenia", "namePt": "Armênia"},
    "aw" : {"nameEn": "Aruba", "namePt": "Aruba"},
    "au" : {"nameEn": "Australia", "namePt": "Austrália"},
    "at" : {"nameEn": "Austria", "namePt": "Áustria"},
    "az" : {"nameEn": "Azerbaijan", "namePt": "Azerbaijão"},
    "bs" : {"nameEn": "Bahamas", "namePt": "Bahamas"},
    "bh" : {"nameEn": "Bahrain", "namePt": "Bahrein"},
    "bd" : {"nameEn": "Bangladesh", "namePt": "Bangladesh"},
    "bb" : {"nameEn": "Barbados", "namePt": "Barbados"},
    "be" : {"nameEn": "Belgium", "namePt": "Bélgica"},
    "bz" : {"nameEn": "Belize", "namePt": "Belize"},
    "bj" : {"nameEn": "Benin", "namePt": "Benim"},
    "bm" : {"nameEn": "Bermuda", "namePt": "Bermudas"},
    "by" : {"nameEn": "Belarus", "namePt": "Bielorrússia"},
    "bo" : {"nameEn": "Bolivia (Plurinational State of)", "namePt": "Bolívia"},
    "ba" : {"nameEn": "Bosnia and Herzegovina", "namePt": "Bósnia e Herzegovina"},
    "bw" : {"nameEn": "Botswana", "namePt": "Botswana"},
    "br" : {"nameEn": "Brazil", "namePt": "Brasil"},
    "bn" : {"nameEn": "Brunei Darussalam", "namePt": "Brunei"},
    "bg" : {"nameEn": "Bulgaria", "namePt": "Bulgária"},
    "bf" : {"nameEn": "Burkina Faso", "namePt": "Burkina Faso"},
    "bi" : {"nameEn": "Burundi", "namePt": "Burundi"},
    "bt" : {"nameEn": "Bhutan", "namePt": "Butão"},
    "cv" : {"nameEn": "Cabo Verde", "namePt": "Cabo Verde"},
    "cm" : {"nameEn": "Cameroon", "namePt": "Camarões"},
    "kh" : {"nameEn": "Cambodia", "namePt": "Camboja"},
    "ca" : {"nameEn": "Canada", "namePt": "Canadá"},
    "kz" : {"nameEn": "Kazakhstan", "namePt": "Cazaquistão"},
    "td" : {"nameEn": "Chad", "namePt": "Chade"},
    "cl" : {"nameEn": "Chile", "namePt": "Chile"},
    "cn" : {"nameEn": "China", "namePt": "China"},
    "cy" : {"nameEn": "Cyprus", "namePt": "Chipre"},
    "co" : {"nameEn": "Colombia", "namePt": "Colômbia"},
    "km" : {"nameEn": "Comoros", "namePt": "Comores"},
    "cg" : {"nameEn": "Congo", "namePt": "República do Congo"},
    "kp" : {"nameEn": "Korea (Democratic People\"s Republic of)", "namePt": "Coreia do Norte"},
    "kr" : {"nameEn": "Korea (Republic of)", "namePt": "Coreia do Sul"},
    "ci" : {"nameEn": "Côte d\"Ivoire", "namePt": "Costa do Marfim"},
    "cr" : {"nameEn": "Costa Rica", "namePt": "Costa Rica"},
    "hr" : {"nameEn": "Croatia", "namePt": "Croácia"},
    "cu" : {"nameEn": "Cuba", "namePt": "Cuba"},
    "dk" : {"nameEn": "Denmark", "namePt": "Dinamarca"},
    "dj" : {"nameEn": "Djibouti", "namePt": "Djibouti"},
    "dm" : {"nameEn": "Dominica", "namePt": "Dominica"},
    "eg" : {"nameEn": "Egypt", "namePt": "Egito"},
    "sv" : {"nameEn": "El Salvador", "namePt": "El Salvador"},
    "ae" : {"nameEn": "United Arab Emirates", "namePt": "Emirados Árabes"},
    "ec" : {"nameEn": "Ecuador", "namePt": "Equador"},
    "er" : {"nameEn": "Eritrea", "namePt": "Eritreia"},
    "sk" : {"nameEn": "Slovakia", "namePt": "Eslováquia"},
    "si" : {"nameEn": "Slovenia", "namePt": "Eslovênia"},
    "es" : {"nameEn": "Spain", "namePt": "Espanha"},
    "fm" : {"nameEn": "Micronesia (Federated States of)", "namePt": "Estados Federados da Micronésia"},
    "us" : {"nameEn": "United States of America", "namePt": "Estados Unidos"},
    "ee" : {"nameEn": "Estonia", "namePt": "Estónia"},
    "et" : {"nameEn": "Ethiopia", "namePt": "Etiópia"},
    "fj" : {"nameEn": "Fiji", "namePt": "Fiji"},
    "ph" : {"nameEn": "Philippines", "namePt": "Filipinas"},
    "fi" : {"nameEn": "Finland", "namePt": "Finlândia"},
    "fr" : {"nameEn": "France", "namePt": "França"},
    "ga" : {"nameEn": "Gabon", "namePt": "Gabão"},
    "gm" : {"nameEn": "Gambia", "namePt": "Gâmbia"},
    "gh" : {"nameEn": "Ghana", "namePt": "Gana"},
    "ge" : {"nameEn": "Georgia", "namePt": "Geórgia"},
    "gd" : {"nameEn": "Grenada", "namePt": "Granada"},
    "gr" : {"nameEn": "Greece", "namePt": "Grécia"},
    "gp" : {"nameEn": "Guadeloupe", "namePt": "Guadalupe"},
    "gu" : {"nameEn": "Guam", "namePt": "Guam"},
    "gt" : {"nameEn": "Guatemala", "namePt": "Guatemala"},
    "gy" : {"nameEn": "Guyana", "namePt": "Guiana"},
    "gf" : {"nameEn": "French Guiana", "namePt": "Guiana Francesa"},
    "gn" : {"nameEn": "Guinea", "namePt": "Guiné"},
    "gq" : {"nameEn": "Equatorial Guinea", "namePt": "Guiné Equatorial"},
    "gw" : {"nameEn": "Guinea-Bissau", "namePt": "Guiné-Bissau"},
    "ht" : {"nameEn": "Haiti", "namePt": "Haiti"},
    "hn" : {"nameEn": "Honduras", "namePt": "Honduras"},
    "hk" : {"nameEn": "Hong Kong", "namePt": "Hong Kong"},
    "hu" : {"nameEn": "Hungary", "namePt": "Hungria"},
    "ye" : {"nameEn": "Yemen", "namePt": "Iêmen"},
    "ky" : {"nameEn": "Cayman Islands", "namePt": "Ilhas Cayman"},
    "ck" : {"nameEn": "Cook Islands", "namePt": "Ilhas Cook"},
    "fo" : {"nameEn": "Faroe Islands", "namePt": "Ilhas Feroé"},
    "sb" : {"nameEn": "Solomon Islands", "namePt": "Ilhas Salomão"},
    "vi" : {"nameEn": "Virgin Islands (U.S.)", "namePt": "Ilhas Virgens Americanas"},
    "vg" : {"nameEn": "Virgin Islands (British)", "namePt": "Ilhas Virgens Britânicas"},
    "in" : {"nameEn": "India", "namePt": "Índia"},
    "id" : {"nameEn": "Indonesia", "namePt": "Indonésia"},
    "gb" : {"nameEn": "United Kingdom of Great Britain and Northern Ireland", "namePt": "Reino unido"},
    "ir" : {"nameEn": "Iran (Islamic Republic of)", "namePt": "Irã"},
    "iq" : {"nameEn": "Iraq", "namePt": "Iraque"},
    "ie" : {"nameEn": "Ireland", "namePt": "Irlanda"},
    "is" : {"nameEn": "Iceland", "namePt": "Islândia"},
    "il" : {"nameEn": "Israel", "namePt": "Israel"},
    "it" : {"nameEn": "Italy", "namePt": "Itália"},
    "jm" : {"nameEn": "Jamaica", "namePt": "Jamaica"},
    "jp" : {"nameEn": "Japan", "namePt": "Japão"},
    "jo" : {"nameEn": "Jordan", "namePt": "Jordânia"},
    "ki" : {"nameEn": "Kiribati", "namePt": "Kiribati"},
    "xk" : {"nameEn": "Republic of Kosovo", "namePt": "Kosovo"},
    "kw" : {"nameEn": "Kuwait", "namePt": "Kuwait"},
    "la" : {"nameEn": "Lao People\"s Democratic Republic", "namePt": "Laos"},
    "ls" : {"nameEn": "Lesotho", "namePt": "Lesoto"},
    "lv" : {"nameEn": "Latvia", "namePt": "Letônia"},
    "lb" : {"nameEn": "Lebanon", "namePt": "Líbano"},
    "lr" : {"nameEn": "Liberia", "namePt": "Libéria"},
    "ly" : {"nameEn": "Libya", "namePt": "Líbia"},
    "li" : {"nameEn": "Liechtenstein", "namePt": "Liechtenstein"},
    "lt" : {"nameEn": "Lithuania", "namePt": "Lituânia"},
    "lu" : {"nameEn": "Luxembourg", "namePt": "Luxemburgo"},
    "mo" : {"nameEn": "Macao", "namePt": "Macau"},
    "mk" : {"nameEn": "Macedonia (the former Yugoslav Republic of)", "namePt": "Macedônia do Norte"},
    "mg" : {"nameEn": "Madagascar", "namePt": "Madagáscar"},
    "my" : {"nameEn": "Malaysia", "namePt": "Malásia"},
    "mw" : {"nameEn": "Malawi", "namePt": "Malawi"},
    "mv" : {"nameEn": "Maldives", "namePt": "Maldivas"},
    "ml" : {"nameEn": "Mali", "namePt": "Mali"},
    "mt" : {"nameEn": "Malta", "namePt": "Malta"},
    "ma" : {"nameEn": "Morocco", "namePt": "Marrocos"},
    "mq" : {"nameEn": "Martinique", "namePt": "Martinica"},
    "mu" : {"nameEn": "Mauritius", "namePt": "Maurícia"},
    "mr" : {"nameEn": "Mauritania", "namePt": "Mauritânia"},
    "mx" : {"nameEn": "Mexico", "namePt": "México"},
    "mm" : {"nameEn": "Myanmar", "namePt": "Mianmar"},
    "mz" : {"nameEn": "Mozambique", "namePt": "Moçambique"},
    "md" : {"nameEn": "Moldova (Republic of)", "namePt": "Moldávia"},
    "mc" : {"nameEn": "Monaco", "namePt": "Mónaco"},
    "mn" : {"nameEn": "Mongolia", "namePt": "Mongólia"},
    "me" : {"nameEn": "Montenegro", "namePt": "Montenegro"},
    "ms" : {"nameEn": "Montserrat", "namePt": "Montserrat"},
    "na" : {"nameEn": "Namibia", "namePt": "Namíbia"},
    "nr" : {"nameEn": "Nauru", "namePt": "Nauru"},
    "np" : {"nameEn": "Nepal", "namePt": "Nepal"},
    "ni" : {"nameEn": "Nicaragua", "namePt": "Nicarágua"},
    "ne" : {"nameEn": "Niger", "namePt": "Níger"},
    "ng" : {"nameEn": "Nigeria", "namePt": "Nigéria"},
    "no" : {"nameEn": "Norway", "namePt": "Noruega"},
    "nc" : {"nameEn": "New Caledonia", "namePt": "Nova Caledônia"},
    "nz" : {"nameEn": "New Zealand", "namePt": "Nova Zelândia"},
    "om" : {"nameEn": "Oman", "namePt": "Omã"},
    "nl" : {"nameEn": "Netherlands", "namePt": "Países Baixos"},
    "pw" : {"nameEn": "Palau", "namePt": "Palau"},
    "ps" : {"nameEn": "Palestine, State of", "namePt": "Palestina"},
    "pa" : {"nameEn": "Panama", "namePt": "Panamá"},
    "pg" : {"nameEn": "Papua New Guinea", "namePt": "Papua-Nova Guiné"},
    "pk" : {"nameEn": "Pakistan", "namePt": "Paquistão"},
    "py" : {"nameEn": "Paraguay", "namePt": "Paraguai"},
    "pe" : {"nameEn": "Peru", "namePt": "Peru"},
    "pf" : {"nameEn": "French Polynesia", "namePt": "Polinésia Francesa"},
    "pl" : {"nameEn": "Poland", "namePt": "Polónia"},
    "pr" : {"nameEn": "Puerto Rico", "namePt": "Porto Rico"},
    "pt" : {"nameEn": "Portugal", "namePt": "Portugal"},
    "qa" : {"nameEn": "Qatar", "namePt": "Catar"},
    "ke" : {"nameEn": "Kenya", "namePt": "Quênia"},
    "kg" : {"nameEn": "Kyrgyzstan", "namePt": "Quirguistão"},
    "cf" : {"nameEn": "Central African Republic", "namePt": "República Centro-Africana"},
    "cz" : {"nameEn": "Czech Republic", "namePt": "República Checa"},
    "tw" : {"nameEn": "Taiwan", "namePt": "Taiwan"},
    "cd" : {"nameEn": "Congo (Democratic Republic of the)", "namePt": "República Democrática do Congo"},
    "do" : {"nameEn": "Dominican Republic", "namePt": "República Dominicana"},
    "ro" : {"nameEn": "Romania", "namePt": "Roménia"},
    "rw" : {"nameEn": "Rwanda", "namePt": "Ruanda"},
    "ru" : {"nameEn": "Russian Federation", "namePt": "Rússia"},
    "mf" : {"nameEn": "Saint Martin (French part)", "namePt": "São Martinho"},
    "ws" : {"nameEn": "Samoa", "namePt": "Samoa"},
    "as" : {"nameEn": "American Samoa", "namePt": "Samoa Americana"},
    "lc" : {"nameEn": "Saint Lucia", "namePt": "Santa Lúcia"},
    "kn" : {"nameEn": "Saint Kitts and Nevis", "namePt": "São Cristóvão e Névis"},
    "sm" : {"nameEn": "San Marino", "namePt": "San Marino"},
    "st" : {"nameEn": "Sao Tome and Principe", "namePt": "São Tomé e Príncipe"},
    "vc" : {"nameEn": "Saint Vincent and the Grenadines", "namePt": "São Vicente e Granadinas"},
    "sn" : {"nameEn": "Senegal", "namePt": "Senegal"},
    "sl" : {"nameEn": "Sierra Leone", "namePt": "Serra Leoa"},
    "rs" : {"nameEn": "Serbia", "namePt": "Sérvia"},
    "sc" : {"nameEn": "Seychelles", "namePt": "Seicheles"},
    "sg" : {"nameEn": "Singapore", "namePt": "Singapura"},
    "sx" : {"nameEn": "Sint Maarten (Dutch part)", "namePt": "São Martinho"},
    "sy" : {"nameEn": "Syrian Arab Republic", "namePt": "Síria"},
    "so" : {"nameEn": "Somalia", "namePt": "Somália"},
    "lk" : {"nameEn": "Sri Lanka", "namePt": "Sri Lanka"},
    "sz" : {"nameEn": "Swaziland", "namePt": "Suazilândia"},
    "sd" : {"nameEn": "Sudan", "namePt": "Sudão"},
    "ss" : {"nameEn": "South Sudan", "namePt": "Sudão do Sul"},
    "se" : {"nameEn": "Sweden", "namePt": "Suécia"},
    "ch" : {"nameEn": "Switzerland", "namePt": "Suíça"},
    "sr" : {"nameEn": "Suriname", "namePt": "Suriname"},
    "tj" : {"nameEn": "Tajikistan", "namePt": "Tajiquistão"},
    "th" : {"nameEn": "Thailand", "namePt": "Tailândia"},
    "tz" : {"nameEn": "Tanzania, United Republic of", "namePt": "Tanzânia"},
    "tl" : {"nameEn": "Timor-Leste", "namePt": "Timor-Leste"},
    "tg" : {"nameEn": "Togo", "namePt": "Togo"},
    "to" : {"nameEn": "Tonga", "namePt": "Tonga"},
    "tt" : {"nameEn": "Trinidad and Tobago", "namePt": "Trinidad e Tobago"},
    "tn" : {"nameEn": "Tunisia", "namePt": "Tunísia"},
    "tc" : {"nameEn": "Turks and Caicos Islands", "namePt": "Turks e Caicos"},
    "tm" : {"nameEn": "Turkmenistan", "namePt": "Turquemenistão"},
    "tr" : {"nameEn": "Turkey", "namePt": "Turquia"},
    "tv" : {"nameEn": "Tuvalu", "namePt": "Tuvalu"},
    "ua" : {"nameEn": "Ukraine", "namePt": "Ucrânia"},
    "ug" : {"nameEn": "Uganda", "namePt": "Uganda"},
    "uy" : {"nameEn": "Uruguay", "namePt": "Uruguai"},
    "uz" : {"nameEn": "Uzbekistan", "namePt": "Uzbequistão"},
    "vu" : {"nameEn": "Vanuatu", "namePt": "Vanuatu"},
    "va" : {"nameEn": "Holy See", "namePt": "Vaticano"},
    "ve" : {"nameEn": "Venezuela (Bolivarian Republic of)", "namePt": "Venezuela"},
    "vn" : {"nameEn": "Viet Nam", "namePt": "Vietnã"},
    "zm" : {"nameEn": "Zambia", "namePt": "Zâmbia"},
    "zw" : {"nameEn": "Zimbabwe", "namePt": "Zimbabwe"}
}

country_names = {countries[country]['namePt']:{'nameEn': countries[country]['nameEn'], 'ISO_2': country} for country in countries}

ls = ['ISL', 'CAN', 'IMN', 'URY', 'NOR', 'AND', 'NLD', 'DEU', 'GBR', 'AUS', 'CHE', 'VUT', 'ARG', 'MLT', 'NZL', 'USA', 'SMR', 'SWE', 'BRA', 'ESP', 'FJI', 'LIE', 'DNK', 'LUX', 'BLZ', 'ZAF', 'FRA', 'CHL', 'FIN', 'BEL', 'MEX', 'CUB', 'ISR', 'AUT', 'PRT', 'IRL', 'CZE', 'SUR', 'CRI', 'MCO', None, 'CPV', 'WSM', 'PLW', 'SYC', 'SVN', 'NPL', 'COL', 'ECU', 'MHL', 'JPN', 'ITA', 'GNQ', 'IND', 'AGO', 'MOZ', 'MUS', 'GRC', 'LAO', 'GNB', 'TWN', 'BOL', None, 'CYP', 'TJK', 'NAM', 'NRU', 'HRV', 'NIC', 'EST', 'FSM', 'PER', 'BTN', 'VEN', 'BWA', 'BHS', 'UZB', 'SLV', 'SVK', 'PHL', 'GTM', 'TLS', 'BGR', 'HND', 'VNM', 'HUN', 'COD', 'STP', 'THA', 'LTU', 'MNE', 'LVA', 'ROU', 'POL', 'SRB', 'KOR', 'BHR', 'TON', 'PAN', 'KIR', 'BIH', 'GEO', 'ALB', 'PNG', 'LSO', 'GAB', 'PRY', 'KHM', 'LKA', 'TKM', 'CHN', 'MNG', 'UKR', 'TTO', 'KGZ', 'BFA', 'TUV', 'DOM', 'ATG', 'GRD', 'IDN', 'BLR', 'MDG', 'LCA', 'TUR', 'MDA', 'MKD', 'RUS', 'HTI', 'KAZ', 'BEN', 'SYR', 'PAK', 'BRB', 'LBN', 'RWA', 'ARM', 'COG', 'MLI', 'CIV', 'SWZ', 'DJI', 'SGP', 'JAM', 'KNA', 'SLB', 'GUY', 'NER', 'MDV', 'SLE', 'AZE', 'ZWE', 'DMA', 'MAR', 'KWT', 'CAF', 'BDI', 'KEN', 'VCT', 'LBR', 'GHA', 'BGD', 'JOR', 'ERI', 'SSD', 'MWI', 'PRK', 'ZMB', 'TGO', 'COM', 'PSE', 'CMR', 'TZA', 'GIN', 'MMR', 'TUN', 'SEN', 'DZA', 'IRQ', 'UGA', 'TCD', 'ETH', 'MYS', 'SDN', 'OMN', 'EGY', 'NGA', 'GMB', 'LBY', 'IRN', 'QAT', 'ARE', 'SOM', 'MRT', 'YEM', 'SAU', 'BRN', 'AFG']
country_dict = {}
for i, country in enumerate(ls):
    country_dict[country] = i