name: Integração Contínua

on: 
  push:
    branches:
      - main

jobs:
  executa_black:
    runs-on: ubuntu-latest
    steps: 
      - name: Action Checkout
        uses: actions/checkout@v2

      - name: Instala o Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
          cache: pip
          
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Executa o black na src
        run: black --check .