name: Deploy manual

on: 
  workflow_run:
    workflows: ["Integração Contínua"]
    branches: [main]
    types:
      - completed

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps: 
      - name: Action Checkout
        uses: actions/checkout@v2
    

      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "geo-lit" #Must be unique in Heroku
          heroku_email: "rpinter811@gmail.com"